# commit to be tagged for the new release
commit = "HEAD"

project_name = "overlays"
github_repo = "siderolabs/overlays"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v1.11.0"
pre_release = true

[notes]
    [rockchip]
        title = "Rockchip SBCS"
	description = """\
New RockChip SBC's have been added:

* odroid-m1
* radxa-zero-3e
* rock3b
* orangepi-5-max
* rock5t
"""
