# commit to be tagged for the new release
commit = "HEAD"

project_name = "overlays"
github_repo = "siderolabs/overlays"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v1.11.4"
pre_release = false

[notes]
